# GitHub org of the repository (optional, `rust-lang` is the default)
#org = "rust-lang"
# Name of the repository
repo = "stdarch"
# Path where the subtree is located in rust-lang/rust
path = "library/stdarch"

# Optionally, you can specify the complete Josh filter for complex cases
# Note that this option is mutually exclusive with `path`
#filter = ...

# Optionally, you can specify a set of commands executed after a successful pull.
# If the executed command changes the local git state (performs some modifications to files that
# were already tracked), then a new commit with the given message will be created.
#[[post-pull]]
#cmd = ["cargo", "fmt"]
#commit-message = "reformat"

# Optionally, you can specify a symmetry filter.
# This will be applied to the local `HEAD` during the round-trip check.
# By default, the round-trip check expects the local repo to be a perfect 1:1 mirror
# of the upstream tree. Leave this empty if that is your intent.
# If you are not doing a 1:1 mirror, set this to a filter that transforms
# your local `HEAD` into a tree that exactly matches the upstream tree.
#sym-filter = ":/rustc_public:exclude[:[::build.rs,::tests/,::Cargo.toml]]:prefix=rustc_public"
